# Generated by Django 6.0.6 on 2026-06-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('strength', models.CharField(blank=True, max_length=255, null=True)),
                ('generic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('dosage_form', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('unit_price', models.CharField(blank=True, max_length=100, null=True)),
                ('strip_price', models.CharField(blank=True, max_length=100, null=True)),
                ('pack_size_info', models.CharField(blank=True, max_length=255, null=True)),
                ('pack_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('indications', models.TextField(blank=True, null=True)),
                ('side_effects', models.TextField(blank=True, null=True)),
                ('pharmacology', models.TextField(blank=True, null=True)),
                ('dosage_administration', models.TextField(blank=True, null=True)),
                ('interaction', models.TextField(blank=True, null=True)),
                ('contraindications', models.TextField(blank=True, null=True)),
                ('pregnancy_lactation', models.TextField(blank=True, null=True)),
                ('precautions_warnings', models.TextField(blank=True, null=True)),
                ('special_populations', models.TextField(blank=True, null=True)),
                ('overdose_effects', models.TextField(blank=True, null=True)),
                ('therapeutic_class', models.TextField(blank=True, null=True)),
                ('storage_conditions', models.TextField(blank=True, null=True)),
                ('chemical_structure', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('reconstitution', models.TextField(blank=True, null=True)),
                ('common_questions', models.TextField(blank=True, null=True)),
                ('alternate_brands', models.TextField(blank=True, null=True)),
                ('innovators_monograph', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
